// Generated by https://quicktype.io

export interface RespuestaPosts {
    ok:     boolean;
    pagina: number;
    posts:  Post[];
}

export interface Post {
    id?:     string;
    mensaje?: string;
    img?:     string[];
    coords?:  string;
    usuario?: Usuario;
    created?: string;
}



export interface Usuario {
    id?:    string;
    nombre?: string;
    avatar?: string;
    email?:  string;
    password?:string;
    rol?: string;
    email_verified_at?: boolean;
    created_at?: Date;
    updated_at?: Date;
}

